# Generated by Django 5.2.6 on 2025-09-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusetin_app', '0003_teammember_testimonial_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Blog cover image', upload_to='blogs/')),
                ('title', models.CharField(help_text='Blog title', max_length=200)),
                ('description', models.TextField(help_text='Blog description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Service image', upload_to='services/')),
                ('title', models.CharField(help_text='Service title', max_length=200)),
                ('description', models.TextField(help_text='Service description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
