# Generated by Django 5.2.6 on 2025-09-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusetin_app', '0005_category_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Application Form', max_length=150)),
                ('pdf', models.FileField(help_text='Upload PDF file only', upload_to='application_forms/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
