# Generated by Django 5.2.6 on 2025-09-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edusetin_app', '0008_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationForm',
        ),
        migrations.RemoveField(
            model_name='application',
            name='city',
        ),
        migrations.RemoveField(
            model_name='application',
            name='university',
        ),
    ]
