# Generated by Django 5.2.6 on 2025-09-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusetin_app', '0013_coursecategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='country_pdfs/'),
        ),
        migrations.AddField(
            model_name='service',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='service_pdfs/'),
        ),
        migrations.AddField(
            model_name='university',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='university_pdfs/'),
        ),
    ]
