# Generated by Django 5.2.6 on 2025-09-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusetin_app', '0014_country_pdf_service_pdf_university_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='course_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
